const PROJECTS_COLLECTION = "projects";
const USERS_COLLECTION = "users";
const TICKETS_COLLECTION = "tickets";
const COMPANY_COLLECTION = "companies";

export {
  PROJECTS_COLLECTION,
  USERS_COLLECTION,
  TICKETS_COLLECTION,
  COMPANY_COLLECTION,
};
